export const ADD_PHOTOS = 'ADD_PHOTOS';
export const REMOVE_PHOTO = 'REMOVE_PHOTO';
export const PHOTOS_FETCH_REQUEST = 'PHOTOS_FETCH_REQUEST';
export const PHOTOS_FETCH_SUCCESS = 'PHOTOS_FETCH_SUCCESS';
export const PHOTOS_FETCH_FAILURE = 'PHOTOS_FETCH_FAILURE';